# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2 # <- Don't forget to change sqlite3 in the gemfile to this.
  encoding: utf8
  pool: 5
  username: root
  password: # Enter password here
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: association_tutorial


production:
  <<: *default
  database: db/production.sqlite3
